name: deploy

on:
  push:
    branches: [master]
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tagName:
        description: "Release version tag name"
        required: false
        default: "latest"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js v16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: init server
        run: |
          yarn --prod --silent
          mkdir -p dist
          cp -r node_modules dist
          cp -r build/* dist
          echo 'start cmd /c "cd dist && node-v16-17-0.exe index.js"' > start.bat

      - name: build
        run: |
          yarn add typescript
          yarn build

      - name: build to zip
        run: |
          zip -r Youtube-Marathon-Timer dist/* public/* start.bat || echo "build to zip error"

      - name: upload Release
        uses: ncipollo/release-action@v1
        if: ${{ inputs.tagName }}
        with:
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ inputs.tagName }}
          artifacts: "Youtube-Marathon-Timer.zip"

      - name: upload Release
        uses: ncipollo/release-action@v1
        if: ${{ !inputs.tagName }}
        with:
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "latest"
          artifacts: "Youtube-Marathon-Timer.zip"
