name: deploy

on:
  push:
    branches: [master]
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js v16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: init server
        run: |
          yarn --prod --silent
          mkdir -p server
          cp -r node_modules server
          cp -r build/* server
          cp -r public
          echo "start server/start.bat" > start.bat

      - name: build
        run: |
          yarn add typescript
          yarn build

      - name: build to zip
        run: |
          zip -r youtube-work-overtime server/* public/* start.bat || echo "build to zip error"

      - name: upload Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "v1"
          artifacts: "youtube-work-overtime.zip"
